Updates for LLM Instruction Tuning
aws-samples/aws-ml-jp pull request #54
Opened 2023-08-21 04:57 UTC by maekawataiki

*Issue #, if available:*

*Description of changes:*
- Add scripts for Falcon and Stable LM JP
- Add sample for wandb in Rinna Notebook

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-21 07:35 UTC, icoxfog417 commented
Notebook の動作確認。

- [X] : Falcon_Inference.ipynb
- [X] : Falcon_LoRA.ipynb
- [X] : Falcon_LoRA_jp.ipynb
- [ ] : Rinna_Neox_LoRA_ja.ipynb
- [ ] : Rinna_Neox_LoRA_ja_djl.ipynb
- [ ] : StableLM_Inference.ipynb
- [ ] : StableLM_Inference_ja.ipynb
- [ ] : StableLM_LoRA.ipynb
- [ ] : StableLM_LoRA_ja.ipynb

2023-08-22 09:44 UTC, maekawataiki commented
- Rinna_Neox_LoRA_ja.ipynb
  - `Model error: cannot import name 'repeat_kv' from 'transformers.models.llama.modeling_llama' (/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py)` というエラーが出ます。`optimum` の課題のようなので一旦無効化しました。https://github.com/huggingface/optimum/issues/1300
- StableLM_Inference.ipynb
  - pad_token_id を指定で動作
- StableLM_LoRA.ipynb
  - pad_token_id を指定で動作
- StableLM_LoRA_ja.ipynb
  - wandb を指定した時のみスクリプト内で `pip install` する挙動に変更。

2023-08-24 14:08 UTC, icoxfog417 requested changes
動作確認済みと伺った Falcon 以外の Notebook の動作確認を完了しました。レビューについて修正もしくは現状で問題ないことを確認いただけたらマージしたいと思います！

2023-08-28 00:46 UTC, maekawataiki commented on tasks/generative-ai/text-to-text/fine-tuning/instruction-tuning/Transformers/StableLM_Inference.ipynb
> -    "        \n",
ありがとうございます、修正しました。

2023-08-28 00:47 UTC, maekawataiki commented on tasks/generative-ai/text-to-text/fine-tuning/instruction-tuning/Transformers/StableLM_Inference.ipynb
>    },
これはおそらく GenerationConfig を使っているからですね。
GenerationConfig は pad_token_id, eos_token_id がデフォルトで None になっているため明示的に指定する必要があるようです。

2023-08-28 00:47 UTC, maekawataiki commented on tasks/generative-ai/text-to-text/fine-tuning/instruction-tuning/Transformers/StableLM_Inference_jp.ipynb
> +    "    \"pad_token_id\": 0,\n",
pad_token_id もしくは eos_token_id が指定されていれば動くようです。一応 bos_token も含めて全て明示的に指定するようにしました。

2023-08-28 13:04 UTC, merged

2023-08-28 13:04 UTC, icoxfog417 commented
修正ありがとうございます！マージしました。